feature: Addition of highway dashboard
sonr-io/highway-sdk pull request #14
Opened 2022-04-11 00:43 UTC by joshLong145

- addition of dashboard react application
- addition of `FS_DIR` env for front end content serving path
- Addition of logger configuration for entry point

2022-04-11 21:06 UTC, ntindle requested changes

2022-04-11 21:06 UTC, ntindle commented on main.go
>  	serverAddress := ":8080"
make this configurable

2022-04-18 15:22 UTC, ntindle approved these changes

2022-04-18 15:23 UTC, merged

2022-04-18 15:24 UTC, brokecollegekidwithaclothingobsession commented on dashboard/package.json
> +    "semantic-ui-css": "^2.4.1",
Are we moving to SemancticUI or going to continue to work with TailwindCSS?